### ISSUE TITLE
Issue with "Subnet-Directed Broadcast" not working

### ISSUE THREAD

**Issue by loitho** [teamhendo/taniumWakeOnLAN#1]
Hi, 
First of all, thank you for those awesome scripts, they're very useful !

I've identified an issue with the "Subnet-Directed Broadcast" : 
https://github.com/teamhendo/taniumWakeOnLAN/blame/d3e72495a5eff4fa6ea9487342b958377ea0040e/wakeController.ps1#L46

$TargetMAC never gets the value "FFFFFFFFFFFF" as the parameter passed by default is FF:FF:FF:FF:FF:FF
![image](https://github.com/user-attachments/assets/75217ad3-9b11-44b4-8279-117063f2c881)

I'm proposing a modification to add a bit more verbose and add a check if the value is FF:FF:FF:FF:FF:FF

**Comment by teamhendo** [comment]
Hey @loitho , thanks for bringing that to my attention. Made some modifications and pushed a change only to then realize I had overlooked the pull request. Still new to back-and-forth flow via GitHub; all my git usage has been local.

**Comment by loitho** [comment]
Hey ! Thank you so much for your quick reply, I can close the merge request if you wish, it contains also some formatting and the removal of some whitespaces in the script, nothing too fancy, but since the main problem is solved it might not be necessary anymore

Also I see you've removed the : 
> $TargetMAC = [System.Uri]::UnescapeDataString("$TargetMAC")

Line, doesn't it cause problem when Tanium runs the script with the escaped char ":" that turns into "%3a" ?

**Comment by loitho** [comment]
I'm closing the MR and Issue as you've put everything in your new commit.
Thank you again for your quick reply and the scripts, they're really really neat and useful !
